services:
  db:
     image: postgres:16-alpine
     restart: unless-stopped
     environment:
        POSTGRES_USER: splitmate
        POSTGRES_PASSWORD: splitmate
        POSTGRES_DB: splitmate
     ports:
        - "5432:5432"
     volumes:
        - splitmate_db_data:/var/lib/postgresql/data

volumes:
  splitmate_db_data: